base_info:
  title: jankin's blog
  author: jankin
  url: https://jankin-z.github.io
style:
  # Theme primary color
  primary_color: "#0066cc"
  avatar: /images/head.jpg
  favicon: /images/CarrotBonus.ico

  # Article image align position, value: left | center
  article_img_align: center

  # # Left side width
  # left_side_width: 260px

  # # Content area max width
  # content_max_width: 920px

  # # Mouse hover
  hover:
    shadow: true # shadow effect when the mouse hover
    scale: true # scale effect when the mouse hover

  # First screen
  first_screen:
    enable: true
    background_img: /images/bg.svg # You can use local image or image external link
    description:  writing and loving.

  # Scroll style settings
  scroll:
    progress_bar:
      enable: true
    percent:
      enable: false

social_contact:
  enable: true
  links:
    github:               # your GitHub URL
    weixin:               # your WeChat QR-Code URL
    qq:                   820520972
    weibo:                # your WeiBo URL
    zhihu:                # your ZhiHu URL
    twitter:              # your twitter URL
    facebook:             # your facebook URL
    email:                jankin_z@139.com
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  Links: /links
  About: /about
  
home_article:
  category:
    enable: false     # show category in home page article block
    limit: 3          # max number of categories shown in home page article block
  tag:
    enable: true     # show tags in home page article block
    limit: 5          # max number of tags shown in home page article block
code_copy:
  enable: true
  style: default        # values: default | mac

post:
  # Post word count
  # Dependencies: hexo-wordcount (npm install hexo-wordcount)
  # See: https://github.com/willin/hexo-wordcount
  word_count:
    enable: false
    wordcount: false  # word count, one article
    min2read: false   # time to read, one article

  # Author label
  author_label:
    enable: true
    auto: false  # if true, show Lv1, Lv2, Lv3... , If false, show custom label
    # label array item can be one or more
    custom_label_list: [ "Trainee", "Engineer", "Architect", "CTO", "BOSS" ]

toc:
  enable: true

  # Automatically add list number to toc.
  number: false

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: false

  # If true, open TOC every time when you enter the article page
  init_open: false

copyright_info:
  enable: true

local_search:
  enable: true
  preload: false     # Preload the search data when the page loads

comment:
  enable: true
  use: valine  # values: valine | gitalk | twikoo

  # Valine
  # See: https://github.com/xCss/Valine
  valine:
    appid:                kFn6rnRydDXsB0UkjbGHrWmM-gzGzoHsz
    appkey:               vGKqMvqppg6NjPEmmMtUoq2R
    placeholder:          😜 尽情吐槽吧~
rss:
  enable: true

lazyload:
  enable: false  

cdn:
  enable: true

pjax:
  enable: true 